package com.springbootfproject.firstWebApp.todomodel;

import java.time.LocalDateTime;
import java.util.UUID;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String transactionId; // Unique ID generated by your application
    private String upiTxnId; // UPI Transaction ID from the UPI application
    private String username;
    private double amount;
    private String upiUrl;
    private String status;
    private LocalDateTime createdAt;

    public Transaction() {
        this.transactionId = UUID.randomUUID().toString();
        this.createdAt = LocalDateTime.now();
        this.status = "PENDING";
    }

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTransactionId() {
		return transactionId;
	}

	public void setTransactionId(String transactionId) {
		this.transactionId = transactionId;
	}

	public String getUpiTxnId() {
		return upiTxnId;
	}

	public void setUpiTxnId(String upiTxnId) {
		this.upiTxnId = upiTxnId;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public double getAmount() {
		return amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public String getUpiUrl() {
		return upiUrl;
	}

	public void setUpiUrl(String upiUrl) {
		this.upiUrl = upiUrl;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public LocalDateTime getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(LocalDateTime createdAt) {
		this.createdAt = createdAt;
	}
    
    // Getters and setters
    
    

   
}

